version: '3.9'
services:
  db:
    build: .
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
